package-lock.json
package.json

Updates the statements service to fix issue.

Fixes "must not contain ." Mongo error.

---

.travis.yml
test.sh

Note that this currently uses [my fork of the conformance tests](https://github.com/adlnet/lrs-conformance-test-suite/pull/222) whilst we wait for adlnet/lrs-conformance-test-suite#221 to be resolved.

Adds conformance tests to Travis.

---

package-lock.json
package.json
yarn.lock

Closes LearningLocker/learninglocker#1016.

Fixes state overwriting by updating xapi-state.

---

package-lock.json
package.json
yarn.lock

LearningLocker/learninglocker#1032

Updates xAPI document services.

---

package-lock.json
package.json
yarn.lock

LearningLocker/learninglocker#1031

Updates xapi-statements to v^2.2.2.

---

package-lock.json
package.json
yarn.lock

This improves error logging! 🎉

Updates xapi-activities, xapi-agents, and xapi-state to ^1.2.0

---

package-lock.json
package.json
src/routers/activities.ts
src/routers/agents.ts
src/routers/state.ts
yarn.lock

Updates xapi-activities to ^2.1.0, xapi-agents to ^2.0.0, and xapi-state to ^2.0.0

---

package-lock.json
package.json
yarn.lock

Closes LearningLocker/learninglocker#1042

Supports invalid alternate requests from Storyline.

---

package-lock.json
package.json
yarn.lock

https://github.com/LearningLocker/learninglocker/issues/1073

Updates xapi-statements to ^5.0.6 to fix more link.

---

.env.example
.gitignore
package-lock.json
package.json
src/config.ts
src/routers/activities.ts
src/routers/agents.ts
src/routers/state.ts
src/routers/statements.ts
yarn.lock

To use this you'll need the following environment variables in the ".env" file.
```
STORAGE_REPO=google
FS_GOOGLE_CLOUD_BUCKET=
FS_GOOGLE_CLOUD_KEY_FILENAME=
FS_GOOGLE_CLOUD_PROJECT_ID=
FS_GOOGLE_CLOUD_BUCKET_SUBFOLDER=
```

feat(storageRepo): Adds support for Google Cloud storage.

---

package-lock.json
package.json
yarn.lock

Contains a patch for https://github.com/LearningLocker/learninglocker/issues/1109

fix(deps): Updates xapi dependencies.

---

package-lock.json
package.json
scripts/updateDeps.js
src/conformanceServer.ts
yarn.lock

Includes [activities v4.1.2](https://github.com/LearningLocker/xapi-activities/releases/tag/v4.1.2), [agents v4.1.2](https://github.com/LearningLocker/xapi-agents/releases/tag/v4.1.2), [state v4.1.2](https://github.com/LearningLocker/xapi-state/releases/tag/v4.1.2), [statements v7.1.2](https://github.com/LearningLocker/xapi-statements/releases/tag/v7.1.2).

fix: Corrects org collection name

---

package-lock.json
package.json
yarn.lock

Includes [activities v4.1.4](https://github.com/LearningLocker/xapi-activities/releases/tag/v4.1.4), [agents v4.1.4](https://github.com/LearningLocker/xapi-agents/releases/tag/v4.1.4), [state v4.1.4](https://github.com/LearningLocker/xapi-state/releases/tag/v4.1.4), [statements v7.1.10](https://github.com/LearningLocker/xapi-statements/releases/tag/v7.1.10).

fix(xapi-statements): Fixes attachment corruption. 

---

package-lock.json
package.json
yarn.lock

Includes [activities v4.2.0](https://github.com/LearningLocker/xapi-activities/releases/tag/v4.2.0), [agents v4.2.0](https://github.com/LearningLocker/xapi-agents/releases/tag/v4.2.0), [state v4.2.0](https://github.com/LearningLocker/xapi-state/releases/tag/v4.2.0), [statements v7.5.0](https://github.com/LearningLocker/xapi-statements/releases/tag/v7.5.0).

feat: Adds OAuth Support.

---

src/apps/statements/repo/modelsRepo/getStatementsByIds/memory.ts
src/apps/statements/repo/modelsRepo/getStatementsByIds/mongo.ts
src/apps/statements/repo/modelsRepo/getUpRefsByIds/memory.ts
src/apps/statements/repo/modelsRepo/getUpRefsByIds/mongo.ts
src/apps/statements/repo/modelsRepo/getVoidersByIds/memory.ts
src/apps/statements/repo/modelsRepo/getVoidersByIds/mongo.ts
src/apps/statements/repo/modelsRepo/getVoidersByObjectIds/memory.ts
src/apps/statements/repo/modelsRepo/getVoidersByObjectIds/mongo.ts
src/apps/statements/tests/store.test.ts

Noticed by James and Asahd in load tests.

fix: Reduces database queries by avoiding queries with empty ins.

---

docker-compose.yml
src/apps/AppConfig.ts
src/apps/statements/AppConfig.ts
src/apps/statements/app.ts
src/apps/statements/errors/Timeout.ts
src/apps/statements/expressPresenter/utils/handleError.ts
src/apps/statements/repo/index.ts
src/apps/statements/repo/modelsRepo/getStatements/mongo/index.ts
src/apps/statements/repo/modelsRepo/utils/mongoModels/FacadeConfig.ts
src/apps/statements/repo/modelsRepo/utils/mongoModels/factory.ts
src/apps/statements/translatorFactory/Translator.ts
src/apps/statements/translatorFactory/en.ts
src/server.ts

https://learningpool.atlassian.net/browse/LLC-339

fix: Ensures statement requests timeout (LLC-339)

---

src/config.ts

https://learningpool.atlassian.net/browse/LLC-364

fix: Reduces default timeout to 55 seconds

---

package.json
src/apps/activities/expressPresenter/postProfile.ts
src/apps/agents/expressPresenter/getFullAgent.ts
src/apps/agents/expressPresenter/postProfile.ts
src/apps/statements/expressPresenter/getFullActivity.ts
src/apps/statements/expressPresenter/postStatements/index.ts
src/apps/states/expressPresenter/postState.ts
yarn.lock

https://learningpool.atlassian.net/browse/LLC-22

fix(deps): Upgrades jscommons for Node 12 upgrade (LLC-22)

---

.env.example
readme.md

Improves setup instructions to make onboarding easier as discussed in the retro.
Relates to https://github.com/LearningLocker/enterprise/pull/1365

docs(Readme): Adds setup instructions

---

src/apps/statements/repo/eventsRepo/emitNewStatements/Signature.ts
src/apps/statements/repo/eventsRepo/emitNewStatements/redis.ts
src/apps/statements/service/storeStatements/index.ts

Closes LLC-[592](https://learningpool.atlassian.net/browse/LLC-592)

feat(API): Add organisation ID to queue jobs that only contain the statement ID (LLC-592)

---

.circleci/config.yml
Dockerfile
package.json
yarn.lock

Closes: https://learningpool.atlassian.net/browse/LLC-22

chore: Upgrades Node v10 to v12 (LLC-22)

---

package.json
yarn.lock

Closes [LLC-1200](https://learningpool.atlassian.net/browse/LLC-1200).

fix(deps): remove jscpd and fix security risks (LLC-1200)

---

package.json
yarn.lock

Closes [LLC-1209](https://learningpool.atlassian.net/browse/LLC-1209).

chore(deps): update dependency jscommons to v3.0.2 (LLC-1209)

---

package.json
yarn.lock

Closes [LLC-1262](https://learningpool.atlassian.net/browse/LLC-1262).

fix(deps): Upgrade normalize-url to v6.0.1 (LLC-1262)

---

.circleci/config.yml
patches/@google-cloud+common+3.6.0.patch

Closes [LLC-1266](https://learningpool.atlassian.net/browse/LLC-1266).

refactor: Update patch to include logs for potential google-cloud write errors (LLC-1266)

---

package.json
yarn.lock

Closes [LLC-1376](https://learningpool.atlassian.net/browse/LLC-1376).

fix(Deps): Upgrade @npmcli/git to 2.0.8 (LLC-1376)

---

.circleci/config.yml

Closes [LLC-1331](https://learningpool.atlassian.net/browse/LLC-1331).

fix(Circle): Update Circle release workflow to ignore test azure and google (LLC-1331)

---

package.json
yarn.lock

Closes [LLC-1383](https://learningpool.atlassian.net/browse/LLC-1383).

fix(Deps): Upgrade @npmcli/arborist using resolutions (LLC-1383)

---

.env.example
src/config.ts

Closes: [LLC-1667](https://learningpool.atlassian.net/browse/LLC-1667)

feat(Config): Adds generic region and access creds for easier stack creation (LLC-1667)

---

package.json
yarn.lock

Closes [LLC-2134](https://learningpool.atlassian.net/browse/LLC-2134).

fix(Deps): Resolve json-schema alert and upgrade semantic-release (LLC-2134)

---

package.json
scripts/updateDeps.js
yarn.lock

Closes [LLC-2151](https://learningpool.atlassian.net/browse/LLC-2151).

chore(deps-dev): bump simple-git from 2.40.0 to 3.5.0 (LLC-2151)

---

package.json

fix(RunTime): Add backward compatibility by removing engines restriction (LLC-2384)
